### ISSUE TITLE
Can't get Electron demo to work

### ISSUE THREAD

**Issue by closedcontour** [tijmenvangulik/ErgometerJS#1] opened 2016-05-30 04:58 UTC
I'm using a Mac and can't get the Electron example to discover my PM5. I've actually tried using noble's example advertisement-discovery.js and it looks like my device is never "discover"ed. 

Have you had success with the Electron version at all?

Thanks!

**Comment by tijmenvangulik** [comment] 2016-05-30 06:57
Yes I am also using a Mac and it workshop fine. Not all Macs have low power blue tooth . Have you checked this?

Tijmen

**Comment by closedcontour** [comment] 2016-05-30 14:14
Thanks for the quick reply.

I have a relatively modern MacBook and just verified in my System Report:

```
Bluetooth Low Energy Supported: Yes
 ...
LMP Version: 0x6
```

I can do some further debugging but let me know if there are any other tips you can give me.

**Comment by tijmenvangulik** [comment] 2016-05-30 14:51
We van compare the machines what is your Mac osx version? Do you have more details on the ble hardware?

Tijmen

**Comment by closedcontour** [comment] 2016-05-30 15:34
I've made some progress but still stuck. I don't think this an issue with ErgometerJS though. I can get noble to discover the device but not connect to it. It just hangs on the Peripheral.connect() call.

**Comment by tijmenvangulik** [comment] 2016-05-30 18:18
Can you Check if you can find the ergometer using light blue. You can download it using this link?

https://itunes.apple.com/us/app/lightblue-explorer-bluetooth/id557428110?mt=8

Some more questions
- What PM5 firmeware do you use? Have you installed the latest version?
- I assume that you have activated the blue tooth on the PM5 device. (Without this you will never find it)

Tijmen

**Comment by closedcontour** [comment] 2016-05-30 21:03
I checked LightBlue. I can't get it to connect to the PM5. Same issue: it discovers but then can't get any further. LightBlue on iOS works fine.

I'm on PM5 v20 (just release v22 is latest). My OS is 10.10.5 (Yosemite).

Thanks for helping but I'm pretty sure this is not a problem with your project!

**Comment by tijmenvangulik** [comment] 2016-05-31 06:30
So it looks like a Mac os x bug or pm5 bug. I Will check my firmware version. The temp Workaround  can be: build and test on iOS. use the record replay feature to test on electron.

Tijmen

**Comment by tijmenvangulik** [comment] 2016-05-31 18:04
This is my setup:

OS X El Captain 10.11.5 (15F34)

Blue tooth:
  Apple Bluetooth Software Version:	4.4.5f3 17904
  Hardware, Features, and Settings:
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	Yes
  Instant Hot Spot Supported:	Yes
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	20702B0
  Firmware Version:	v118 c9121
  Bluetooth Power:	On
  Discoverable:	Off
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x8289
  HCI Version:	4.0 (0x6)
  HCI Revision:	0x23A1
  LMP Version:	4.0 (0x6)
  LMP Subversion:	0x4176
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

PM5
"hardwareRevision":"340”,"
firmwareRevision”:20

**Comment by tijmenvangulik** [comment] 2016-06-04 08:24
I close this issue because the problem is likely to be something it the OS or hardware. But I am still interesed if you found a sollution.

**Closed by tijmenvangulik** 2016-06-04 08:24 UTC

**Comment by closedcontour** [comment] 2016-06-04 17:57
I upgraded to El Capitan (10.11.5) and everything works. Thanks.
